const PREGUNTAS5J = {
    "A": ["Comienza por ", "Cuando se aproxima la última hora de la tarde, decimos que está..."],
    "B": ["Comienza por ", "Es una ciudad al norte de España muy famosa por sus morcillas. Es..."],
    "C": ["Comienza por ", "La hermana mayor de Phineas y Ferb se llama..."],
    "D": ["Comienza por ", "Qué bonita es la corona que llevas en el pelo. Anda, no es una corona porque está abierta por detrás. Es una..."],
    "E": ["Comienza por ", "Tengo que barrer, pero no encuentro la..."],
    "F": ["Comienza por ", "Antes no lo conocía nadie. Pero ha salido en la tele y ahora se ha hecho..."],
    "G": ["Comienza por ", "San Sebastián es famosa por su comida. Todo el mundo aprecia su..."],
    "H": ["Comienza por ", "Me he mojado tanto que se me han calado hasta los..."],
    "I": ["Comienza por ", "Como sigas portándote mal te voy a llevar un mes a un..."],
    "J": ["Comienza por ", "Es un municipio de Alicante muy famoso por sus turrones. Es un turrón de..."],
    "L": ["Comienza por ", "Es parecido al limón, aunque también es el nombre de la capital de Perú. Es una..."],
    "M": ["Comienza por ", "Ya sé que es de noche y muy tarde, pero como no madrugo, seguiré en casa de mi amigo hasta la...."],
    "N": ["Comienza por ", "Es la casa de los pájaros. Lo suelen construir con ramas. Es un..."],
    "Ñ": ["Contiene la ", "Madrid es la capital de..."],
    "O": ["Comienza por ", "Si la televisión tiene telespectadores, la radio tiene..."],
    "P": ["Comienza por ", "Pablo Picasso fue un gran...."],
    "Q": ["Contiene la ", "Es una comida redonda y ovalada hecha con bechamel y a la que se le ponen cosas dentro antes de freirla. Es la famosa..."],
    "R": ["Comienza por ", "Cuando voy en el coche me gusta ir escuchando la..."],
    "S": ["Comienza por ", "Te lo cuento pero no se lo cuentes a nadie. Es un..."],
    "T": ["Comienza por ", "Esta mancha no se quita en la lavadora. Vas a tener que llevar la prenda en una..."],
    "U": ["Comienza por ", "Es un supervillano que se enfrenta a los vengadores y que se llama..."],
    "V": ["Comienza por ", "Es un piloto de motos italiano y cuyo apellido es Rossi. Es muy valiente. Su nombre es..."],
    "X": ["Comienza por ", "Creo que tengo un dedo roto. Me harán una radiografía y para ello usarán los rayos..."],
    "Y": ["Contiene la ", "La mesa de la cocina está muy sucia. Pasa una..."],
    "Z": ["Comienza por ", "Yo compro mi ropa en una famosa tienda del grupo Inditex que pertenece a Amancio Ortega. La tienda se llama..."],
};