// PREGUNTAS1 en este caso es el identificador del set de preguntas
const PREGUNTAS4 = {
    "A": ["Comienza por ", "Tierra de color ocre usada en jardineria y en las plazas de toras."],
    "B": ["Comienza por ", "Echar al agua un buque haciéndolo resbalar por la grada después de construido."],
    "C": ["Comienza por ", "Punto de unión de ciertas partes similares del cuerpo, como los labios y los párpados."],
    "D": ["Comienza por ", "Diminutivo de diablo."],
    "E": ["Comienza por ", "Hacer aprecio y estimación"],
    "F": ["Comienza por ", "Que defiende con mucha vehemencia ideas, opiniones y creencias religiosas o políticas."],
    "G": ["Comienza por ", "Disfrutar mucho."],
    "H": ["Comienza por ", "Pieza metálica o de otro material, que se emplea para sujetar el pelo."],
    "I": ["Comienza por ", "Broma en el día de los Santos Inocentes."],
    "J": ["Comienza por ", "Acción destacada de un juego."],
    "L": ["Comienza por ", "Perteneciente o relativo a la lira."],
    "M": ["Comienza por ", "Aparato que detecta las fuerzas magnéticas."],
    "N": ["Comienza por ", "Parte exterior de cualquiera de las junturas de los dedos."],
    "Ñ": ["Contiene la ", "Que rebaña."],
    "O": ["Comienza por ", "Que carece de luz."],
    "P": ["Comienza por ", "Instrumento de hierro o de otro material rematado en punta, que sirve para abrir ojetes y para otros usos."],
    "Q": ["Comienza por ", "Tortilla de maíz rellena de queso u otros ingredientes que se come caliente."],
    "R": ["Comienza por ", "Volver a plantar árboles y otras especies vegetales en un lugar."],
    "S": ["Comienza por ", "Dar un salto."],
    "T": ["Comienza por ", "Revista infantil de historietas cuyo asunto se desarrolla en series de dibujos."],
    "U": ["Comienza por ", "Nombre del escritor italiano, de apellido Eco, autor de El nombre de la rosa."],
    "V": ["Comienza por ", "Que habita con otros en un mismo pueblo, barrio o casa, en habitación independiente."],
    "X": ["Contiene la ", "Que es adecuado o está destinado tanto para los hombres como para las mujeres."],
    "Y": ["Comienza por ", "Uno de los más famosos portales de internet."],
    "Z": ["Comienza por ", "Acción y efecto de zurcir."],
};