const PREGUNTAS2 = {
    "A": ["Comienza por ", "Si un barco quiere quedarse quieto en el mar, debe soltar su..."],
    "B": ["Comienza por ", "La capital de Colombia es..."],
    "C": ["Comienza por ", "Así llamamos también a las golosinas. Son las..."],
    "D": ["Comienza por ", "¿Es grave doctor?. Cuénteme cuál es su..."],
    "E": ["Comienza por ", "Es una persona que no puede tener hijos. Es..."],
    "F": ["Comienza por ", "Nos acordamos del pasado. Vivimos el presente. Y miramos hacia el..."],
    "G": ["Comienza por ", "Mi coche no duerme en la calle. Lo aparco siempre en un..."],
    "H": ["Comienza por ", "Los nietos de mis padres son mis..."],
    "I": ["Comienza por ", "He terminado mi enseñanza primaria en el colegio. Ahora haré la enseñanza secundaria en el..."],
    "J": ["Comienza por ", "En una peli de Disney, Aladdin se enamora de la princesa..."],
    "L": ["Comienza por ", "Antes de montar una pizzería, primero tendré que buscar un buen..."],
    "M": ["Comienza por ", "El año tiene doce..."],
    "N": ["Comienza por ", "Es el penúltimo mes del año. Es..."],
    "Ñ": ["Contiene la ", "A la caca la llamamos de muchas maneras graciosas. Por ejemplo zurullo, mojón, ñordo o..."],
    "O": ["Comienza por ", "La tierra tiene en la atmósfera una capa que nos protege de la radiación ultravioleta y que se llama capa de..."],
    "P": ["Comienza por ", "Antes del Euro, la moneda que se usaba en España era la..."],
    "Q": ["Contiene la ", "La mitad de mil son..."],
    "R": ["Comienza por ", "La capital de Italia es..."],
    "S": ["Comienza por ", "Este negocio lo montaré con otra persona. Será mi..."],
    "T": ["Comienza por ", "A lo lejos se ve un torbellino de aire que llega hasta las nubes y está girando. Es un..."],
    "U": ["Comienza por ", "Así llamamos a los que han nacido en Uruguay. Son..."],
    "V": ["Comienza por ", "Nadie se presentó al puesto de trabajo que ofrecían. El puesto quedó.."],
    "X": ["Contiene la ", "El científico no para de probar cosas en su laboratorio. Está realizando..."],
    "Y": ["Contiene la ", "Mañana debuto en la obra de teatro pero aún no domino las frases que tengo que decir. Necesito seguir..."],
    "Z": ["Contiene la ", "Lo contrario de guerra es..."],
};