const PREGUNTAS2 = {
    "Comienza por A": "Si un barco quiere quedarse quieto en el mar, debe soltar su...",
    "Comienza por B": "La capital de Colombia es...",
    "Comienza por C": "Así llamamos también a las golosinas. Son las...",
    "Comienza por D": "¿Es grave doctor?. Cuénteme cuál es su...",
    "Comienza por E": "Es una persona que no puede tener hijos. Es...",
    "Comienza por F": "Nos acordamos del pasado. Vivimos el presente. Y miramos hacia el...",
    "Comienza por G": "Mi coche no duerme en la calle. Lo aparco siempre en un...",
    "Comienza por H": "Los nietos de mis padres son mis...",
    "Comienza por I": "He terminado mi enseñanza primaria en el colegio. Ahora haré la enseñanza secundaria en el...",
    "Comienza por J": "En una peli de Disney, Aladdin se enamora de la princesa...",
    "Comienza por L": "Antes de montar una pizzería, primero tendré que buscar un buen...",
    "Comienza por M": "El año tiene doce...",
    "Comienza por N": "Es el penúltimo mes del año. Es...",
    "Contiene la Ñ": "A la caca la llamamos de muchas maneras graciosas. Por ejemplo zurullo, mojón, ñordo o...",
    "Comienza por O": "La tierra tiene en la atmósfera una capa que nos protege de la radiación ultravioleta y que se llama capa de...",
    "Comienza por P": "Antes del Euro, la moneda que se usaba en España era la...",
    "Contiene la Q": "A la caca la llamamos de muchas maneras graciosas. Por ejemplo zurullo, mojón, ñordo o...",
    "Comienza por R": "La capa de caperucita es de color...",
    "Comienza por S": "Si quieres que tu ropa se seque más rápido, métela en la....",
    "Comienza por T": "Te tropiezas siempre. Eres un poco...",
    "Comienza por U": "Comprende todo el universo. Es...",
    "Comienza por V": "Es el segundo planeta más próximo al sol. También es la diosa del amor en la mitologia griega. Es...,
    "Contiene la X": "El pecho de las personas y de los animales también se llama...",
    "Comienza por Y": "En inglés, (amarillo) se dice...",
    "Comienza por Z": "Es como un lobo. Es muy astuto y le encanta entrar en los corrales de noche. Es un...",
};