// PREGUNTAS1 en este caso es el identificador del set de preguntas
const PREGUNTAS2 = {
    "A": ["Comienza por ", "Idioma árabe."],
    "B": ["Comienza por ", "Deporte parecido al tenis que se juega con raquetas pequeñas de mango largo y un volante."],
    "C": ["Comienza por ", "Caja ósea en que está contenido el encéfalo."],
    "D": ["Comienza por ", "Relativo a los dedos."],
    "E": ["Comienza por ", "Alto y delgado."],
    "F": ["Comienza por ", "Que está en la parte delantera, se encuentra enfrente o se produce de frente."],
    "G": ["Comienza por ", "Lleno de grasa."],
    "H": ["Comienza por ", "Señal que deja el pie del hombre o del animal en la tierra por donde pasa."],
    "I": ["Comienza por ", "Crear algo en la imaginación."],
    "J": ["Comienza por ", "Sitio poblado de juncos."],
    "L": ["Comienza por ", "Herir o hacer daño."],
    "M": ["Comienza por ", "Recipiente de barro cocido, que suele tener un agujero en la parte inferior, y que, lleno de tierra, sirve para criar plantas. "],
    "N": ["Comienza por ", "Cualidad o actitud de neutral."],
    "Ñ": ["Comienza por ", "Que es cursi, pasado de moda y anticuado."],
    "O": ["Comienza por ", "Que ha recibido alguna ofensa."],
    "P": ["Comienza por ", "Caballo de una raza que es producto del cruce de la arabe con las del norte de Europa."],
    "Q": ["Contiene la ", "Indisposición o enfermedad habitual, especialmente las que acompañan a la vejez."],
    "R": ["Comienza por ", "Se dice del alimento o bebida viejos, de sabor y olor desagradables."],
    "S": ["Comienza por ", "Emperador turco."],
    "T": ["Comienza por ", "Pieza con que se tapan las vasijas, introduciéndola en el orificio por donde sale el líquido."],
    "U": ["Comienza por ", "Parte de la medicina referente al aparato urinario."],
    "V": ["Comienza por ", "Que se alimenta mayormente de vegetales."],
    "X": ["Contiene la ", "Lo que pasa más allá de la medida o regla."],
    "Y": ["Comienza por ", "Par de bueyes, mulas u otros animales que sirven en la labor del campo o en los acarreos."],
    "Z": ["Comienza por ", "Exfutbolista hispano-chileno que jugó en el Sevilla y el Real Madrid."],
};