const PREGUNTAS4J = {
    "A": ["Comienza por ", "El piloto localizó la pista de aterrizaje y colocó el avión en posición para poder"],
    "B": ["Comienza por ", "En la capital de Argentina siempre tiene el aire fresco. Por eso la capital se llama…"],
    "C": ["Comienza por ", "En el bollo me ha tocado de regalo una pegatina que se pone en la mano, se moja y el dibujo aparece en la mano. Es una..."],
    "D": ["Comienza por ", "A Cruella de Vil le encantan las pieles. Sobre todo de los..."],
    "E": ["Comienza por ", "Me acabo de comprar unos zapatos y esta noche los voy a..."],
    "F": ["Comienza por ", "Tienes que poner la calefacción ya. Aquí dentro hace demasiado.."],
    "G": ["Comienza por ", "Esos niños no son mellizos. Aunque nacieron en el mismo parto, son..."],
    "H": ["Comienza por ", "Menuda herida más fea. Tienes que ir rapidamente a un..."],
    "I": ["Comienza por ", "En Australia, el idioma que se utiliza es el..."],
    "J": ["Comienza por ", "La persona que más manda en una jerarquia es el ..."],
    "L": ["Comienza por ", "Para besar necesitamos los ..."],
    "M": ["Comienza por ", "El Guggenheim de Bibao, el Prado de Madrid o el Macba de Barcelona, son..."],
    "N": ["Comienza por ", "Tengo ganas de que llegue diciembre y empiece la ..."],
    "Ñ": ["Contiene la ", "A los aragoneses también se les conoce con el nombre de…"],
    "O": ["Comienza por ", "Si quedo en la primera posición me darán una medalla de..."],
    "P": ["Comienza por ", "Hay que atrapar al ladrón. Necesitamos ayuda. Llamemos a la…"],
    "Q": ["Comienza por ", "Es una ave carroñera que le encanta quebrar los huesos."],
    "R": ["Comienza por ", "Es la nota musical que va antes de Mi y después de DO. Es..."],
    "S": ["Comienza por ", "Esta comida está muy sosa. Necesito poner un poco de..."],
    "T": ["Comienza por ", "Cuando trabajas desde casa, se dice que estás..."],
    "U": ["Comienza por ", "Debemos votar todos lo mismo. El voto tiene que ser unánime. Debemos votar con..."],
    "V": ["Comienza por ", "Si exprimimos las uvas y el zumo obtenido lo cocemos y fermentamos, obtenemos …"],
    "X": ["Contiene la ", "No podemos estar más felices. Hemos alcanzado el..."],
    "Y": ["Contiene la ", "Si mi hermano me saca dos años, entonces es que es mi hermano..."],
    "Z": ["Comienza por ", "Debemos excavar siguiendo la carretera. Debemos excavar una ..."],
};