const PREGUNTAS1J = {
    "A": ["Comienza por ", "En primavera no puedo acercarme mucho a las flores porque tengo un poco de..."],
    "B": ["Comienza por ", "No es un diamante, pero brilla. Es un..."],
    "C": ["Comienza por ", "No tengo dinero en la cartera. Tengo que sacar dinero. Seguro que ese banco tiene un..."],
    "D": ["Comienza por ", "La capital de Irlanda es..."],
    "E": ["Comienza por ", "Está rodeando el edificio. El ladrón ha desaparecido al doblar la..."],
    "F": ["Comienza por ", "Para que sea válido el contrato debes poner tu..."],
    "G": ["Comienza por ", "Para ponerme en forma, esta semana iré todos los días al..."],
    "H": ["Comienza por ", "El accidente fue grave pero afortunadamente no hubo..."],
    "I": ["Comienza por ", "El teléfono de Apple se llama..."],
    "J": ["Comienza por ", "Es un famoso municipio de la provincia de Huesca. A pocos kilómetros están las estaciones de Astún y Candanchú. Es..."],
    "L": ["Comienza por ", "Estaba tan triste que no pudo evitar que de sus ojos se derramaran unas..."],
    "M": ["Comienza por ", "Pregunta Es un poco impreciso, pero sobre las 12 de la mañana decimos que es la mitad del día, es decir, que es..."],
    "N": ["Comienza por ", "Pregunta La persona que trafica con drogas decimos que es un..."],
    "Ñ": ["Contiene la ", "Cuando nos referimos a un tiempo pasado, decimos que fue..."],
    "O": ["Comienza por ", "Si la televisión tiene telespectadores, la radio tiene.."],
    "P": ["Comienza por ", "Más fácil no es posible. Es este juego y se llama..."],
    "Q": ["Contiene la ", "La mitad de mil son..."],
    "R": ["Comienza por ", "La capital de Italia es..."],
    "S": ["Comienza por ", "Este negocio lo montaré con otra persona. Será mi..."],
    "T": ["Comienza por ", "A lo lejos se ve un torbellino de aire que llega hasta las nubes y está girando. Es un..."],
    "U": ["Comienza por ", "Así llamamos a los que han nacido en Uruguay. Son..."],
    "V": ["Comienza por ", "Nadie se presentó al puesto de trabajo que ofrecían. El puesto quedó.."],
    "X": ["Contiene la ", "El científico no para de probar cosas en su laboratorio. Está realizando..."],
    "Y": ["Contiene la ", "Mañana debuto en la obra de teatro pero aún no domino las frases que tengo que decir. Necesito seguir..."],
    "Z": ["Contiene la ", "Lo contrario de guerra es..."],
};