const PREGUNTAS2J = {
    "A": ["Comienza por ", "La sirenita se llama como un detergente. Su nombre es..."],
    "B": ["Comienza por ", "Los barcos pueden ir a estribor o a..."],
    "C": ["Comienza por ", "Para la playa, mejor que ir con zapatos, te aconsejo que te pongas unas..."],
    "D": ["Comienza por ", "El cielo está enladrillado. ¿Quién lo..."],
    "E": ["Comienza por ", "Una escalera está compuesta por muchos..."],
    "F": ["Comienza por ", "Para poder calentar agua en una olla necesitas encender el..."],
    "G": ["Comienza por ", "Para desayunar prefiero un café con leche y poder mojar dentro unas..."],
    "H": ["Comienza por ", "La asignatura en la que se estudia lo que ha ocurrido en el pasado, se llama..."],
    "I": ["Comienza por ", "El famoso impuesto del valor añadido, solemos nombrarlo por sus iniciales, que son..."],
    "J": ["Comienza por ", "Eres muy aficionado a la juerga. Eres un..."],
    "L": ["Comienza por ", "Es el mejor amigo de Mario Bros y se llama..."],
    "M": ["Comienza por ", "El que más manda en un ministerio es el...."],
    "N": ["Comienza por ", "Oeste, este, sur y..."],
    "Ñ": ["Contiene la ", "Al excremento de las vacas le llamamos..."],
    "O": ["Comienza por ", "No está a la vista. Lo he escondido. Está..."],
    "P": ["Comienza por ", "La persona que preside un gobierno se llama..."],
    "Q": ["Comienza por ", "Para comprar cualquier periódico o revista, nada mejor que ir a un..."],
    "R": ["Comienza por ", "Es una canción del Dúo Dinámico que se hizo muy popular durante el confinamiento provocado por el Coronavirus. Se llama..."],
    "S": ["Comienza por ", "Cien años son un..."],
    "T": ["Comienza por ", "Para poder hablar con alguien que está en otro lugar usamos el..."],
    "U": ["Comienza por ", "Es el séptimo planeta más próximo al sol. Y no tiene ano. Su nombre es..."],
    "V": ["Comienza por ", "Me gustan más los barcos que van a motor que los que van a …."],
    "X": ["Comienza por ", "La xenofobia es tener fobia a los extranjeros. Y quien tiene xenofobia es un..."],
    "Y": ["Contiene la ", "Mi mascota es un conejillo de Indias, también conocido como una..."],
    "Z": ["Comienza por ", "Es un cristal de color azul que se usa mucho para crear joyas. Es el..."],
};