// PREGUNTAS1 en este caso es el identificador del set de preguntas
const PREGUNTAS3 = {
    "A": ["Comienza por ", "Profundidad grande, imponente y peligrosa."],
    "B": ["Comienza por ", "Actividad manual realizada en la propia vivienda sin acudir a profesionales."],
    "C": ["Comienza por ", "Conocido como verdadero y seguro."],
    "D": ["Comienza por ", "Duodécimo mes del año."],
    "E": ["Comienza por ", "Perteneciente o relativo al obispo."],
    "F": ["Comienza por ", "Conjunto de hojas y ramas de un grupo de árboles o arbustos."],
    "G": ["Comienza por ", "Espesor de algo."],
    "H": ["Comienza por ", "Que hostiga."],
    "I": ["Comienza por ", "Molestar, importunar."],
    "J": ["Comienza por ", "Pedazo desgarrado del vestido o de otra ropa."],
    "L": ["Comienza por ", "Intensamente pálido."],
    "M": ["Comienza por ", "Natural de Madrid."],
    "N": ["Comienza por ", "Altura a la que llega la superficie de un líquido."],
    "Ñ": ["Contiene la ", "Con disgusto o repugnancia de hacer algo."],
    "O": ["Comienza por ", "Sección necrológica de un periódico."],
    "P": ["Comienza por ", "Erupción en los labios."],
    "Q": ["Comienza por ", "Acción y efecto de quebrar."],
    "R": ["Comienza por ", "Volver a plantear un problema o asunto."],
    "S": ["Comienza por ", "Recipiente para sopa."],
    "T": ["Comienza por ", "Pastel grande, de forma generalmente redonda, relleno de frutas, crema, etc."],
    "U": ["Comienza por ", "Persona que se encarga de la ropa y el material deportivo de los jugadores de determinados deportes."],
    "V": ["Comienza por ", "Parte de tierra baja, Ilana y fértil."],
    "X": ["Contiene la ", "Acción y efecto de excluir."],
    "Y": ["Comienza por ", "Natural de Yugoslavia."],
    "Z": ["Comienza por ", "Torre escalonada y piramidal, característica de la arquitectura religiosa asiria y caldea."],
};