// PREGUNTAS1 en este caso es el identificador del set de preguntas
const PREGUNTAS5 = {
    "A": ["Comienza por ", "Imputar a alguien de algún delito."],
    "B": ["Comienza por ", "Saco más o menos pequeño cosido en una u otra parte de los vestidos."],
    "C": ["Comienza por ", "Serie de montañas enlazadas entre sí."],
    "D": ["Comienza por ", "Situar a alguien o algo fuera de lugar."],
    "E": ["Comienza por ", "Perteneciente o relativo al Estado."],
    "F": ["Comienza por ", "Sensible a la luz."],
    "G": ["Comienza por ", "Filtración de agua a través de un techo."],
    "H": ["Comienza por ", "Aparato culinario cerrado, en cuyo interior se asan, calientan o gratinan alimentos."],
    "I": ["Comienza por ", "Que no se puede quemar."],
    "J": ["Comienza por ", "Apellido del vocalista de los Rolling Stones."],
    "L": ["Comienza por ", "Acción de amamantar o de mamar."],
    "M": ["Comienza por ", "Que tiene majestad."],
    "N": ["Comienza por ", "Del color y brillo del nácar."],
    "Ñ": ["Contiene la ", "Conjunto de acciones militares ofensivas y defensivas con continuidad temporal desarrolladas en un mismo territorio."],
    "O": ["Comienza por ", "En el juego del mus, envite del resto."],
    "P": ["Comienza por ", "Destreza del tirador para dar en el blanco."],
    "Q": ["Contiene la ", "Inflamación aguda o crónica de los bronquios."],
    "R": ["Comienza por ", "Subida o aumento que experimenta cualquier hecho, fenómeno o proceso."],
    "S": ["Comienza por ", "Dar sazón a la comida."],
    "T": ["Comienza por ", "Conjunto de programas televisivos de muy baja calidad."],
    "U": ["Comienza por ", "Atar o juntar una cosa con otra."],
    "V": ["Comienza por ", "Pronosticar, adivinar, profetizar."],
    "X": ["Contiene la ", "Expulsar a alguien de un territorio."],
    "Y": ["Comienza por ", "Planta de América tropical, de la familia de las Liliáceas, con tallo arborescente, cilíndrico, lleno de cicatrices."],
    "Z": ["Comienza por ", "Acción y efecto de zapatear."],
};