const PREGUNTAS2 = {
    "Comienza por A": "En primavera no puedo acercarme mucho a las flores porque tengo un poco de...",
    "Comienza por B": "No es un diamante, pero brilla. Es un...",
    "Comienza por C": "No tengo dinero en la cartera. Tengo que sacar dinero. Seguro que ese banco tiene un...",
    "Comienza por D": "La capital de Irlanda es...",
    "Comienza por E": "Está rodeando el edificio. El ladrón ha desaparecido al doblar la...",
    "Comienza por F": "Para que sea válido el contrato debes poner tu...",
    "Comienza por G": "Para ponerme en forma, esta semana iré todos los días al...",
    "Comienza por H": "El accidente fue grave pero afortunadamente no hubo...",
    "Comienza por I": "El teléfono de Apple se llama...",
    "Comienza por J": "Es un famoso municipio de la provincia de Huesca. A pocos kilómetros están las estaciones de Astún y Candanchú. Es...",
    "Comienza por L": "Estaba tan triste que no pudo evitar que de sus ojos se derramaran unas...",
    "Comienza por M": "Pregunta Es un poco impreciso, pero sobre las 12 de la mañana decimos que es la mitad del día, es decir, que es...",
    "Comienza por N": "Pregunta La persona que trafica con drogas decimos que es un...",
    "Contiene la Ñ": "Cuando nos referimos a un tiempo pasado, decimos que fue...",
    "Comienza por O": "Si la televisión tiene telespectadores, la radio tiene..",
    "Comienza por P": "Más fácil no es posible. Es este juego y se llama...",
    "Contiene la Q": "La mitad de mil son...º",
    "Comienza por R": "La capital de Italia es...",
    "Comienza por S": "Este negocio lo montaré con otra persona. Será mi...",
    "Comienza por T": "A lo lejos se ve un torbellino de aire que llega hasta las nubes y está girando. Es un...",
    "Comienza por U": "Así llamamos a los que han nacido en Uruguay. Son...º",
    "Comienza por V": "Nadie se presentó al puesto de trabajo que ofrecían. El puesto quedó..",
    "Contiene la X": "El científico no para de probar cosas en su laboratorio. Está realizando...",
    "Contiene la Y": "Mañana debuto en la obra de teatro pero aún no domino las frases que tengo que decir. Necesito seguir...",
    "Contiene la Z": "Lo contrario de guerra es...",
};