// PREGUNTAS1 en este caso es el identificador del set de preguntas
const PREGUNTAS6 = {
    "A": ["Comienza por ", "Que tiene buena suerte o fortuna."],
    "B": ["Comienza por ", "Lugar donde se guarda y cría el vino."],
    "C": ["Comienza por ", "Perteneciente o relativo al culteranismo."],
    "D": ["Comienza por ", "Digno de desprecio."],
    "E": ["Comienza por ", "Capa o nivel."],
    "F": ["Comienza por ", "Robusto y de mucho hueso."],
    "G": ["Comienza por ", "Bien parecido."],
    "H": ["Comienza por ", "Bebida hecha con chufas u otros frutos, machacados, exprimidos y mezclados con agua y azúcar."],
    "I": ["Comienza por ", "Que carece de comodidad"],
    "J": ["Comienza por ", "Superior en la jerarquía eclesiástica."],
    "L": ["Comienza por ", "Color rubio oscuro, como el del pelo de los leones."],
    "M": ["Comienza por ", "Acción y efecto de maltratar."],
    "N": ["Comienza por ", "Recién hecho o fabricado."],
    "Ñ": ["Contiene la ", "Cada uno de los pelos que hay en los bordes de los párpados, para defensa de los ojos."],
    "O": ["Comienza por ", "Que tiene ojeras."],
    "P": ["Comienza por ", "Perteneciente o relativo al niño o a la puericia."],
    "Q": ["Contiene la ", "Casilla o depósito para recibir el agua y distribuirla."],
    "R": ["Comienza por ", "Cauteloso, reacio en manifestar su interior."],
    "S": ["Comienza por ", "Que no se ha casado."],
    "T": ["Comienza por ", "Propensión o inclinación en los hombres y en las cosas hacia determinados fines."],
    "U": ["Comienza por ", "Sola y sin otra de su especie."],
    "V": ["Comienza por ", "Que dilata los vasos sanguíneos."],
    "X": ["Contiene la ", "A excepción de."],
    "Y": ["Comienza por ", "En la jerga de la droga, adicto a la heroína."],
    "Z": ["Comienza por ", "Lugar en que se conservan, cuidan y a veces se crían diversas especies animales con fines didácticos o de entretenimiento."],
};