const PREGUNTAS1 = {
    "Comienza por A": "La sirenita se llama como un detergente. Su nombre es...",
    "Comienza por B": "Los barcos pueden ir a estribor o a...",
    "Comienza por C": "Para la playa, mejor que ir con zapatos, te aconsejo que te pongas unas...",
    "Comienza por D": "El cielo está enladrillado. ¿Quién lo...",
    "Comienza por E": "Una escalera está compuesta por muchos...",
    "Comienza por F": "Para poder calentar agua en una olla necesitas encender el...",
    "Comienza por G": "Para desayunar prefiero un café con leche y poder mojar dentro unas...",
    "Comienza por H": "La asignatura en la que se estudia lo que ha ocurrido en el pasado, se llama...",
    "Comienza por I": "El famoso impuesto del valor añadido, solemos nombrarlo por sus iniciales, que son...",
    "Comienza por J": "Eres muy aficionado a la juerga. Eres un...",
    "Comienza por L": "Es el mejor amigo de Mario Bros y se llama...",
    "Comienza por M": "El que más manda en un ministerio es el....",
    "Comienza por N": "Oeste, este, sur y...",
    "Contiene la Ñ": "Al excremento de las vacas le llamamos...",
    "Comienza por O": "No está a la vista. Lo he escondido. Está...",
    "Comienza por P": "La persona que preside un gobierno se llama...",
    "Comienza por Q": "Para comprar cualquier periódico o revista, nada mejor que ir a un...",
    "Comienza por R": "Es una canción del Dúo Dinámico que se hizo muy popular durante el confinamiento provocado por el Coronavirus. Se llama...",
    "Comienza por S": "Cien años son un...",
    "Comienza por T": "Para poder hablar con alguien que está en otro lugar usamos el...",
    "Comienza por U": "Es el séptimo planeta más próximo al sol. Y no tiene ano. Su nombre es...º",
    "Comienza por V": "Me gustan más los barcos que van a motor que los que van a ….",
    "Comienza por X": "La xenofobia es tener fobia a los extranjeros. Y quien tiene xenofobia es un...",
    "Contiene la Y": "Mi mascota es un conejillo de Indias, también conocido como una...",
    "Comienza por Z": "Es un cristal de color azul que se usa mucho para crear joyas. Es el...",
};