const PREGUNTAS3J = {
    "A": ["Comienza por ", "Si un barco quiere quedarse quieto en el mar, debe soltar su..."],
    "B": ["Comienza por ", "La capital de Colombia es..."],
    "C": ["Comienza por ", "Así llamamos también a las golosinas. Son las..."],
    "D": ["Comienza por ", "¿Es grave doctor?. Cuénteme cuál es su..."],
    "E": ["Comienza por ", "Es una persona que no puede tener hijos. Es..."],
    "F": ["Comienza por ", "Nos acordamos del pasado. Vivimos el presente. Y miramos hacia el..."],
    "G": ["Comienza por ", "Mi coche no duerme en la calle. Lo aparco siempre en un..."],
    "H": ["Comienza por ", "Los nietos de mis padres son mis..."],
    "I": ["Comienza por ", "He terminado mi enseñanza primaria en el colegio. Ahora haré la enseñanza secundaria en el..."],
    "J": ["Comienza por ", "En una peli de Disney, Aladdin se enamora de la princesa..."],
    "L": ["Comienza por ", "Antes de montar una pizzería, primero tendré que buscar un buen..."],
    "M": ["Comienza por ", "El año tiene doce..."],
    "N": ["Comienza por ", "Es el penúltimo mes del año. Es..."],
    "Ñ": ["Contiene la ", "A la caca la llamamos de muchas maneras graciosas. Por ejemplo zurullo, mojón, ñordo o..."],
    "O": ["Comienza por ", "La tierra tiene en la atmósfera una capa que nos protege de la radiación ultravioleta y que se llama capa de..."],
    "P": ["Comienza por ", "Antes del Euro, la moneda que se usaba en España era la..."],
    "Q": ["Contiene la ", "D'Artagnan siempre está acompañado de sus tres fieles..."],
    "R": ["Comienza por ", "La capa de caperucita es de color..."],
    "S": ["Comienza por ", "Si quieres que tu ropa se seque más rápido, métela en la...."],
    "T": ["Comienza por ", "Te tropiezas siempre. Eres un poco..."],
    "U": ["Comienza por ", "Comprende todo el universo. Es..."],
    "V": ["Comienza por ", "Es el segundo planeta más próximo al sol. También es la diosa del amor en la mitologia griega. Es..."],
    "X": ["Contiene la ", "El pecho de las personas y de los animales también se llama..."],
    "Y": ["Comienza por ", "En inglés se dice --> Amarillo"],
    "Z": ["Comienza por ", "Es como un lobo. Es muy astuto y le encanta entrar en los corrales de noche. Es un..."],
};