const PREGUNTAS6J = {
    "A": ["Comienza por ", "Es una marca de ropa de deporte. Compite contra Nike. Es..."],
    "B": ["Comienza por ", "Su capital es Brasilia.El pais es..."],
    "C": ["Comienza por ", " En Halloween es muy tipico vaciarlas y crear una cara. Dentro solemos poner una vela. Es la....."],
    "D": ["Comienza por ", "Para poder quitar el corcho de una botella de vino, hay que..."],
    "E": ["Comienza por ", "Te han visto besar a esa chica. Ya verás cuando se enteren los demás. Va a ser un..."],
    "F": ["Comienza por ", "Esta guerra hay que ganarla. Hagámonos fuertes en este lugar y construyamos una..."],
    "G": ["Comienza por ", "Que bien vistes. Qué elegante y como conquistas a los demás con tu saber estar. Eres todo un...."],
    "H": ["Comienza por ", "Esa pared se ha mojado. Le ha salido una..."],
    "I": ["Comienza por ", "La rueda, la brújula, el papel... surgieron gracias a que el ser humano los creó. Los....."],
    "J": ["Comienza por ", "Es la forma de hablar que usamos con nuestros amigos. Es la..."],
    "L": ["Comienza por ", "Por mucho que calientes el bizcocho en el horno, no crecerá hasta que no le pongas..."],
    "M": ["Comienza por ", "No te preocupes. Si me tienes que localizar puedes llamarme al..."],
    "N": ["Comienza por ", "Este documento lo debe firmar un notario. Busquemos una..."],
    "Ñ": ["Contiene la ", "La vaca no tiene pies, tiene..."],
    "O": ["Comienza por ", "Que bien habla en público. Su oratoria es extraordinaria. Es un gran..."],
    "P": ["Comienza por ", "El barco tiene roto el motor. Hay que remolcarlo hasta el..."],
    "Q": ["Contiene la ", "Fue culpa del otro coche. No respetó el semáforo en rojo y no pude evitar el..."],
    "R": ["Comienza por ", "El color característico de los coches Ferrari es el..."],
    "S": ["Comienza por ", "Así se llama también a una monja o religiosa. Nos referimos a ella como..."],
    "T": ["Comienza por ", "Es un insecto parecido a la hormiga que se come la madera. Es la..."],
    "U": ["Comienza por ", "El martillo, los destornilladores, la taladradora... para un albañil, son parte de sus herramientas de trabajo. Son sus..."],
    "V": ["Comienza por ", "Caracas es la capital de..."],
    "X": ["Contiene la ", "Se sale de lo ordinario. Es mucho más. Es..."],
    "Y": ["Comienza por  ", "Es una de las más famosas plataformas de internet. Es de los principales buscadores de webs. Es..."],
    "Z": ["Comienza por ", "Fue jugador y ahora es entrenador. Su nombre es Zinedine y su apellido es..."],
};