// PREGUNTAS1 en este caso es el identificador del set de preguntas
const PREGUNTAS1 = {
    "A": ["Comienza por ", "Hilo de cualquier metal."],
    "B": ["Comienza por ", "Repartir publicidad o propaganda en los buzones de las casas particulares."],
    "C": ["Comienza por ", "Especie de iglesia pequeña habitualmente para uso particular."],
    "D": ["Comienza por ", "Ser supremo que en las religiones monoteístas es considerado hacedor del universo."],
    "E": ["Comienza por ", "Que no tiene principio ni fin."],
    "F": ["Comienza por ", "Arrugar la frente y las cejas en señal de desabrimiento o de ira."],
    "G": ["Comienza por ", "Adorno femenino que rodea la garganta."],
    "H": ["Comienza por ", "Rastrear con el olfato algo."],
    "I": ["Comienza por ", "Acusar de algún crimen o delito."],
    "J": ["Comienza por ", "Deliberar acerca de la culpabilidad de alguien, o de la razón que le asiste en un asunto, y sentenciar lo procedente."],
    "L": ["Comienza por ", "Dar lustre y brillantez a algo."],
    "M": ["Comienza por ", "Parte interna del tronco de los árboles, fibrosa y compacta, cubierta por la corteza de este."],
    "N": ["Comienza por ", "Que se puede numerar."],
    "Ñ": ["Comienza por ", "Ave corredora americana, muy veloz, que habita las grandes llanuras."],
    "O": ["Comienza por ", "Obra teatral cuyo texto se canta."],
    "P": ["Comienza por ", "Capacidad que tiene alguien para aguantar o tolerar algo sin exaltar sus ánimos."],
    "Q": ["Contiene la ", "Presumida, esmerada en su arreglo personal"],
    "R": ["Comienza por ", "Persona cuyo nombre consta en el remite de un sobre o paquete."],
    "S": ["Comienza por ", "Cantidad que resulta de una cuenta."],
    "T": ["Comienza por ", "Dicho de una persona: Pasar la noche, o gran parte de ella, velando o sin dormir."],
    "U": ["Comienza por ", "Ciudad, especialmente la muy populosa."],
    "V": ["Comienza por ", "Dos veces diez."],
    "X": ["Contiene la ", "Habitación o vivienda con vistas a la calle."],
    "Y": ["Comienza por ", "Colocado junto a algo o en posición inmediata a algo."],
    "Z": ["Comienza por ", "Andar vagando de una parte a otra sin trabajar."],
};